[project]
name = "sync-life-ha"
version = "0.1.0"
description = "Integration sync life with Home Assistant"
requires-python = ">=3.13.5"
dependencies = [
    "homeassistant>=2025.8.0",
    "peewee>=3.18.1",
]
