vehicle_update_mileage:
  name: "Vehicle: update mileage"
  description: "Atualiza a kilometragem do veículo escolhido"
  fields:
    device_id:
      name: Veículo
      required: true
      selector:
        device:
          filter:
            - integration: synclife
              manufacturer: FIAT
            - integration: synclife
              manufacturer: HYUNDAI
            - integration: synclife
              manufacturer: HONDA
    mileage:
      name: Kilometragem
      required: true
      selector:
        number:

nutrition_intake_supplement:
  name: "Nutrition: intake supplement"
  description: "Insere um suplemento para uma pessoa"
  fields:
    person_id:
      name: Pessoa
      required: true
      selector:
        entity:
          domain:
            - person
    supplement:
      name: Suplemento
      required: true
      selector:
        text:
    amount:
      name: Quantidade
      required: true
      selector:
        number:
    taken_at:
      name: Data e hora
      required: false
      selector:
        datetime: {}

finance_transaction_monthly:
  name: "Finance: register monthly transaction"
  description: "Registra pagamento da despesa ou recebimento da receita"
  fields:
    plan_id:
      name: ID do registro
      required: true
      selector:
        number:

sleep_event:
  name: "Sleep: save event"
  description: "Evento para indicar se esta acordando ou dormindo"
  fields:
    person_id:
      name: Pessoa
      required: true
      selector:
        entity:
          domain:
            - person
    action:
      name: Ação
      required: true
      selector:
        text:

nutrition_liquid_intake:
  name: "Nutrition: intake liquids"
  description: "Insere um liquido para uma pessoa"
  fields:
    person_id:
      name: Pessoa
      required: true
      selector:
        entity:
          domain:
            - person
    liquid:
      name: Liquido
      required: true
      selector:
        text:
    amount:
      name: Quantidade
      required: true
      selector:
        number:
    taken_at:
      name: Data e hora
      required: false
      selector:
        datetime: {}